
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ghegun
 */
public class FormPendaftaran extends javax.swing.JDialog {
    List<Pengguna> listPendaftaran = new ArrayList<>();
    private Pengguna Pendaftaran;
    
    public FormPendaftaran(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        initState();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNoPendaftaran = new javax.swing.JLabel();
        jLabelIdPegawai = new javax.swing.JLabel();
        jLabelNoAntrian = new javax.swing.JLabel();
        jLabelTanggalDaftar = new javax.swing.JLabel();
        jLabelKodePasien = new javax.swing.JLabel();
        jLabelKeluhan = new javax.swing.JLabel();
        jLabelKodeDokter = new javax.swing.JLabel();
        jLabelBiaya = new javax.swing.JLabel();
        TxtNoPendaftaran = new javax.swing.JTextField();
        TxtIdPegawai = new javax.swing.JTextField();
        TxtTgl = new javax.swing.JTextField();
        TxtNoAntrian = new javax.swing.JTextField();
        TxtKodePasien = new javax.swing.JTextField();
        TxtKeluhan = new javax.swing.JTextField();
        TxtKodeDokter = new javax.swing.JTextField();
        TxtBiaya = new javax.swing.JTextField();
        Bulan = new com.toedter.calendar.JMonthChooser();
        Tahun = new com.toedter.calendar.JYearChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_daftar = new javax.swing.JTable();
        BtnSimpan = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        BtnEdit = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        Pesan_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.SystemColor.controlHighlight);

        jLabelNoPendaftaran.setText("No Pendaftaran");

        jLabelIdPegawai.setText("ID Pegawai");

        jLabelNoAntrian.setText("No Antrian");

        jLabelTanggalDaftar.setText("Tanggal Daftar");

        jLabelKodePasien.setText("Kode Pasien");

        jLabelKeluhan.setText("Keluhan");

        jLabelKodeDokter.setText("Kode Dokter");

        jLabelBiaya.setText("Biaya");

        TxtNoPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNoPendaftaranActionPerformed(evt);
            }
        });

        TxtTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTglActionPerformed(evt);
            }
        });

        TxtKodePasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodePasienActionPerformed(evt);
            }
        });

        TxtKeluhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKeluhanActionPerformed(evt);
            }
        });

        TxtKodeDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeDokterActionPerformed(evt);
            }
        });

        TxtBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBiayaActionPerformed(evt);
            }
        });

        tabel_daftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Pendaftaran", "ID Pegawai", "No Antrian", "Tanggal Daftar", "Kode Pasien", "Keluhan", "Kode Dokter", "Biaya"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_daftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_daftarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_daftar);

        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnEdit.setText("Edit");
        BtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditActionPerformed(evt);
            }
        });

        BtnHapus.setText("Hapus");

        Pesan_Error.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNoPendaftaran)
                            .addComponent(jLabelIdPegawai)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTanggalDaftar)
                                    .addComponent(jLabelKodePasien)
                                    .addComponent(jLabelNoAntrian))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtNoAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtNoPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtKodePasien, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelKodeDokter)
                                            .addComponent(jLabelKeluhan)
                                            .addComponent(jLabelBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtKodeDokter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Pesan_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BtnSimpan)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnEdit, BtnHapus, BtnSimpan, BtnTambah});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelNoPendaftaran)
                            .addComponent(TxtNoPendaftaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelIdPegawai)
                            .addComponent(TxtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(TxtNoAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNoAntrian))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(TxtTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTanggalDaftar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelKodePasien)
                                    .addComponent(TxtKodePasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pesan_Error, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnSimpan)
                                    .addComponent(BtnTambah)
                                    .addComponent(BtnEdit)
                                    .addComponent(BtnHapus)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabelKodeDokter)
                                    .addComponent(TxtKodeDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(107, 107, 107))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabelKeluhan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(TxtKeluhan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNoPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNoPendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNoPendaftaranActionPerformed

    private void TxtKodePasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodePasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodePasienActionPerformed

    private void TxtKeluhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKeluhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKeluhanActionPerformed

    private void TxtBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtBiayaActionPerformed

    private void TxtKodeDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodeDokterActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        Pesan_Error.setText("");
        DefaultTableModel model=(DefaultTableModel) tabel_daftar.getModel();
        if(!TxtNoPendaftaran.getText().trim().equals("")){
            model.addRow(new Object[]{TxtNoPendaftaran.getText(), 
            TxtIdPegawai.getText(),TxtTgl.getText(),TxtNoAntrian.getText(),
            TxtTgl.getText(), TxtKodePasien.getText(), 
            TxtKeluhan.getText(), TxtKodeDokter.getText(), 
            TxtBiaya.getText()});
        }else{
            Pesan_Error.setText("Kolom Harus Terisi Tidak Boleh Kosong");
        } 
        
        SwingUtil swingUtil = new SwingUtil();
        swingUtil.setActive(true, TxtNoPendaftaran, TxtIdPegawai, TxtTgl, 
                            TxtKodePasien, TxtNoAntrian, TxtKeluhan,
                            TxtKodeDokter, TxtBiaya );
        BtnSimpan.setEnabled(true);
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
      String getTxtNoPendaftaran = TxtNoPendaftaran.getText();
      String getTxtIdPegawai = TxtIdPegawai.getText();
      String getTxtNoAntrian = TxtNoAntrian.getText();
      String getTxtTgl = TxtTgl.getText();
      String getTxtKodePasien = TxtKodePasien.getText();
      String getTxtKeluhan = TxtKeluhan.getText();
      String getTxtKodeDokter = TxtKodeDokter.getText();
      String getTxtBiaya =TxtBiaya.getText();
      
      Pendaftaran pendaftaran = new Pendaftaran(getTxtNoPendaftaran, getTxtIdPegawai, getTxtNoAntrian, getTxtTgl, getTxtKodePasien, getTxtKeluhan, getTxtKodeDokter, getTxtBiaya);
      
      listPendaftaran.add(Pendaftaran);
      
      
      
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void TxtTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTglActionPerformed

    private void BtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditActionPerformed
        Pesan_Error.setText("");
        DefaultTableModel model=(DefaultTableModel) tabel_daftar.getModel();
       if(tabel_daftar.getSelectedRow()==-1){
           if(tabel_daftar.getRowCount()==0){
               Pesan_Error.setText("Tabel Kosong");
           }else{
               Pesan_Error.setText("Anda Harus Pilih Daftar Tabel");
           }
       }else{
            model.setValueAt(TxtNoPendaftaran.getText(), tabel_daftar.getSelectedRow(), 0);
            model.setValueAt(TxtIdPegawai.getText(), tabel_daftar.getSelectedRow(), 1);
            model.setValueAt(TxtNoAntrian.getText(), tabel_daftar.getSelectedRow(), 2);
            model.setValueAt(TxtTgl.getText(), tabel_daftar.getSelectedRow(), 3);
            model.setValueAt(TxtKodePasien.getText(), tabel_daftar.getSelectedRow(), 4);
            model.setValueAt(TxtKeluhan.getText(), tabel_daftar.getSelectedRow(), 5);
            model.setValueAt(TxtKodeDokter.getText(), tabel_daftar.getSelectedRow(), 6);
            model.setValueAt(TxtBiaya.getText(), tabel_daftar.getSelectedRow(), 7);
            }
    }//GEN-LAST:event_BtnEditActionPerformed

    private void tabel_daftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_daftarMouseClicked
        DefaultTableModel model=(DefaultTableModel) tabel_daftar.getModel();
        TxtNoPendaftaran.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 0).toString());
        TxtIdPegawai.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 1).toString());
        TxtNoAntrian.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 2).toString());
        TxtTgl.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 3).toString());
        TxtKodePasien.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 4).toString());
        TxtKeluhan.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 5).toString());
        TxtKodeDokter.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 6).toString());
        TxtBiaya.setText(model.getValueAt(tabel_daftar.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_tabel_daftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPendaftaran dialog = new FormPendaftaran(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEdit;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnTambah;
    private com.toedter.calendar.JMonthChooser Bulan;
    private javax.swing.JLabel Pesan_Error;
    private com.toedter.calendar.JYearChooser Tahun;
    private javax.swing.JTextField TxtBiaya;
    private javax.swing.JTextField TxtIdPegawai;
    private javax.swing.JTextField TxtKeluhan;
    private javax.swing.JTextField TxtKodeDokter;
    private javax.swing.JTextField TxtKodePasien;
    private javax.swing.JTextField TxtNoAntrian;
    private javax.swing.JTextField TxtNoPendaftaran;
    private javax.swing.JTextField TxtTgl;
    private javax.swing.JLabel jLabelBiaya;
    private javax.swing.JLabel jLabelIdPegawai;
    private javax.swing.JLabel jLabelKeluhan;
    private javax.swing.JLabel jLabelKodeDokter;
    private javax.swing.JLabel jLabelKodePasien;
    private javax.swing.JLabel jLabelNoAntrian;
    private javax.swing.JLabel jLabelNoPendaftaran;
    private javax.swing.JLabel jLabelTanggalDaftar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_daftar;
    // End of variables declaration//GEN-END:variables

    private void initState() {
        SwingUtil swingUtil = new SwingUtil();
        swingUtil.setActive(false, TxtNoPendaftaran, TxtIdPegawai, TxtNoAntrian, TxtTgl, TxtKodePasien, TxtKeluhan, TxtKodeDokter, TxtBiaya);
        swingUtil.setActive(false, Bulan, Tahun);
        swingUtil.setActive(false, BtnSimpan, BtnEdit,BtnHapus );
    }

    private void tampilData() {
        
    }
}
